"""add_loker_checks_table

Revision ID: 3f9026ea7493
Revises: ccd4e06a5ab5
Create Date: 2026-05-31 16:37:01.119333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9026ea7493'
down_revision: Union[str, Sequence[str], None] = 'ccd4e06a5ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loker_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('info_source', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('scam_percentage', sa.Float(), nullable=True),
    sa.Column('scam_category', sa.String(), nullable=True),
    sa.Column('scam_reason', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loker_checks_id'), 'loker_checks', ['id'], unique=False)
    op.create_index(op.f('ix_loker_checks_user_id'), 'loker_checks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loker_checks_user_id'), table_name='loker_checks')
    op.drop_index(op.f('ix_loker_checks_id'), table_name='loker_checks')
    op.drop_table('loker_checks')
    # ### end Alembic commands ###
